Adds Build and Publish Steps
steviecoaster/TreasureChest pull request #2
Opened 2021-07-07 18:37 UTC by JPRuskin

2021-07-07 19:44 UTC, steviecoaster requested changes
One nit, the rest LGTM!

2021-07-07 19:44 UTC, steviecoaster commented on build.ps1
> +            Build-Module -SemVer $SemVer
Me thinks we need a check for `Build-Module` here and install the required module if not found. Unless I'm holding how to use this build script wrong now with these changes?

2021-07-07 20:36 UTC, JPRuskin commented on build.ps1
> +            Build-Module -SemVer $SemVer
I've got a Requirements.ps1 to install prereqs - should I just run that within the build script?

2021-07-07 20:38 UTC, JPRuskin commented on build.ps1
> +                choco pack $Nuspec.FullName --output-directory $root
I also forgot to ensure the Build action downloads this zip - will make sure that happens.

2021-07-08 09:49 UTC, JPRuskin commented on treasuredocs/mkdocs.yml
>  repo_url: https://github.com/steviecoaster/TreausureChest
```suggestion
repo_url: https://github.com/steviecoaster/NexuShell
```
(Assuming you'll be updating the repo name - having said that, I guess this `repo_url` doesn't need to be correct)

2021-07-08 09:50 UTC, JPRuskin commented on treasuredocs/mkdocs.yml
>  repo_url: https://github.com/steviecoaster/TreausureChest
Foldername this is in may also want changing.

2021-07-09 16:09 UTC, closed without merging